require: rubocop-rails
AllCops:
  Exclude:
    - ‘bin/**/*’
    - ‘config/**/*’
    - ‘coverage/**/*’
    - ‘db/**/*’
    - ‘lib/**/*’
    - ‘log/**/*’
    - ‘public/**/*’
    - ‘tmp/**/*’
    - ‘spec/**/*’
    - ‘vendor/**/*’
    - ‘./*’
    - 'db/schema.rb'
    - 'db/migrate/20210116223636_create_active_storage_tables.active_storage.rb'
    - 'config/environments/development.rb'
    - 'bin/update'
    - 'bin/setup'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
